from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "clientes.html"
GUARD = ROOT / "homeeasy-page-guard.js"
OUTPUT = ROOT / "clientes-conectado-v31.html"

source = SOURCE.read_text(encoding="utf-8")
guard = GUARD.read_text(encoding="utf-8")

if "#pantalla-inicio" not in source or "#pantalla-resultados" not in source:
    raise SystemExit("clientes.html no tiene la estructura esperada")
if "'clientes.html': 'clientes.read'" not in guard:
    raise SystemExit("No se encontró el permiso clientes.read en el guard")

source = source.replace(
    'content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"',
    'content="width=device-width, initial-scale=1.0, viewport-fit=cover"',
    1,
)

guard = guard.replace(
    "'clientes.html': 'clientes.read',",
    "'clientes.html': 'clientes.read',\n        'clientes-conectado-v31.html': 'clientes.read',",
    1,
)
external_guard = '<script src="homeeasy-page-guard.js?v=3.6"></script>'
if external_guard not in source:
    raise SystemExit("No se encontró la referencia al guard 3.6")
source = source.replace(
    external_guard,
    '<script id="clientes-v31-inline-guard">\n' + guard + '\n</script>',
    1,
)

source = source.replace(
    "window.history.replaceState({}, '', `clientes.html?search=${cedula}`);",
    "window.history.replaceState({}, '', window.location.pathname + '?search=' + encodeURIComponent(cedula));",
)
source = source.replace(
    "window.history.replaceState({}, '', 'clientes.html');",
    "window.history.replaceState({}, '', window.location.pathname);",
)
source = source.replace('<body>', '<body class="clientes-connected-v31">', 1)

preview_root = '\n        <div id="clientes-v31-connected" aria-live="polite"></div>\n'
marker = '        <div class="container">'
if marker not in source:
    raise SystemExit("No se encontró el contenedor legado de resultados")
source = source.replace(marker, preview_root + marker, 1)

CSS = r'''
<style id="clientes-connected-v31-style">
body.clientes-connected-v31{--v31-brand:#B2566C;--v31-brand-dark:#92465a;--v31-brand-soft:#f8eef1;--v31-gold:#c2a468;--v31-gold-soft:#fbf5e8;--v31-ink:#1d1d1f;--v31-muted:#7b7b80;--v31-line:#e9e7e8;--v31-bg:#f7f7f8;--v31-card:#fff;--v31-green:#24745d;--v31-green-soft:#eaf6f0;--v31-red:#b23d4d;--v31-red-soft:#fff0f1;--v31-shadow:0 16px 42px rgba(42,31,35,.055)}
body.clientes-connected-v31 #pantalla-resultados{padding:0!important;min-height:100dvh!important;background:var(--v31-bg)!important}
body.clientes-connected-v31 #pantalla-resultados>.header-mini,body.clientes-connected-v31 #pantalla-resultados>.container{display:none!important}
#clientes-v31-connected{display:none;min-height:100dvh;background:var(--v31-bg);padding-bottom:calc(34px + env(safe-area-inset-bottom,0px));color:var(--v31-ink)}
#clientes-v31-connected.is-visible{display:block}#clientes-v31-connected *{box-sizing:border-box}#clientes-v31-connected button{font:inherit}
.v31-header{position:sticky;top:0;z-index:30;background:rgba(247,247,248,.92);-webkit-backdrop-filter:blur(22px) saturate(150%);backdrop-filter:blur(22px) saturate(150%);border-bottom:1px solid rgba(60,60,67,.06)}
.v31-header-inner{width:min(calc(100% - 24px),720px);min-height:82px;margin:0 auto;padding:calc(10px + env(safe-area-inset-top,0px)) 0 10px;display:grid;grid-template-columns:46px 1fr auto;align-items:center;gap:10px}
.v31-back{width:44px;height:44px;border:0;border-radius:50%;background:#fff;color:var(--v31-brand);box-shadow:0 7px 20px rgba(0,0,0,.055);display:grid;place-items:center;font-size:18px}
.v31-title{display:flex;align-items:center;justify-content:center;gap:8px;font-size:21px;font-weight:780;letter-spacing:-.035em;white-space:nowrap}.v31-title img{width:20px;height:auto;display:block}
.v31-new-search{height:44px;border-radius:999px;padding:0 15px;border:1.2px solid var(--v31-brand);background:rgba(255,255,255,.78);color:var(--v31-brand);font-size:13px;font-weight:730;white-space:nowrap}
.v31-shell{width:min(calc(100% - 24px),720px);margin:16px auto 0}.v31-card{background:var(--v31-card);border:1px solid rgba(60,60,67,.075);border-radius:27px;box-shadow:var(--v31-shadow)}
.v31-loading{margin:32px auto;padding:28px 22px;max-width:380px;text-align:center;background:#fff;border:1px solid var(--v31-line);border-radius:24px;box-shadow:var(--v31-shadow);color:var(--v31-muted)}.v31-loading i{display:block;margin:0 auto 12px;color:var(--v31-brand);font-size:23px}
.v31-contact{padding:23px 20px 18px}.v31-identity{display:grid;grid-template-columns:78px minmax(0,1fr) 42px;gap:15px;align-items:center}.v31-avatar{position:relative;width:78px;height:78px;border-radius:50%;background:linear-gradient(145deg,#fbf6f6,#f4e8ec);display:grid;place-items:center;color:var(--v31-brand);font-size:35px;font-weight:720;letter-spacing:-.04em}.v31-avatar-badge{position:absolute;right:-3px;bottom:3px;width:27px;height:27px;border-radius:50%;background:#fff;box-shadow:0 5px 14px rgba(0,0,0,.1);display:grid;place-items:center}.v31-avatar-badge img{width:17px;height:auto}.v31-name{font-size:27px;font-weight:810;letter-spacing:-.045em;line-height:1.08;margin:0;overflow-wrap:anywhere}.v31-id-label{margin-top:8px;color:var(--v31-muted);font-size:12px;font-weight:600}.v31-id{margin-top:2px;font-size:16px;font-weight:640}.v31-more{width:40px;height:40px;border:1px solid var(--v31-line);border-radius:50%;background:#faf9fa;color:var(--v31-brand);display:grid;place-items:center;font-size:17px}
.v31-contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:0;margin-top:22px}.v31-contact-item{min-height:76px;display:grid;grid-template-columns:44px minmax(0,1fr);gap:12px;align-items:center;padding:8px 14px 8px 0;text-decoration:none;color:inherit}.v31-contact-item:nth-child(2){padding-left:17px;border-left:1px solid var(--v31-line)}.v31-contact-icon{width:42px;height:42px;border-radius:50%;background:var(--v31-brand-soft);color:var(--v31-brand);display:grid;place-items:center;font-size:17px}.v31-contact-label{font-size:12px;color:var(--v31-muted);font-weight:590;margin-bottom:5px}.v31-contact-value{font-size:15px;font-weight:650;letter-spacing:-.02em;line-height:1.3;overflow-wrap:anywhere}.v31-email{margin-top:4px;min-height:60px;display:flex;align-items:center;gap:12px;color:var(--v31-muted);border-bottom:1px solid var(--v31-line);padding:4px 0 16px;font-size:14px}.v31-email .v31-contact-icon{flex:0 0 auto;background:#f7f5f6;color:#969399}
.v31-contact-actions{display:grid;grid-template-columns:1fr 52px;gap:12px;margin-top:18px}.v31-whatsapp{height:52px;border:0;border-radius:18px;background:var(--v31-brand);color:#fff;font-size:17px;font-weight:760;display:flex;align-items:center;justify-content:center;gap:10px;box-shadow:0 10px 24px rgba(178,86,108,.20)}.v31-whatsapp i{font-size:21px}.v31-more-bottom{height:52px;border:1px solid var(--v31-line);border-radius:50%;background:#fff;color:var(--v31-brand);font-size:18px}
.v31-summary{margin-top:14px;background:#fff;border:1px solid rgba(60,60,67,.07);border-radius:22px;min-height:70px;box-shadow:0 12px 30px rgba(28,24,23,.04);display:grid;grid-template-columns:44px 1fr;align-items:center;padding:11px 15px}.v31-summary-icon{width:40px;height:40px;border-radius:50%;background:var(--v31-gold-soft);color:var(--v31-gold);display:grid;place-items:center;font-size:16px}.v31-summary-text{display:flex;align-items:center;justify-content:center;gap:8px;flex-wrap:wrap;font-size:14px;line-height:1.3}.v31-summary-text strong{font-weight:760}.v31-summary-text .pending{color:var(--v31-brand);font-weight:780}.v31-dot{color:var(--v31-gold);font-weight:900}
.v31-tabs{margin-top:16px;background:#ecebed;border-radius:18px;padding:3px;display:grid;grid-template-columns:1fr 1fr}.v31-tab{height:48px;border:0;border-radius:15px;background:transparent;color:#77777c;font-size:16px;font-weight:680;position:relative;display:flex;align-items:center;justify-content:center;gap:7px}.v31-tab.is-active{background:#fff;color:var(--v31-brand);box-shadow:0 4px 14px rgba(0,0,0,.055)}.v31-tab.is-active:after{content:"";position:absolute;left:17%;right:17%;bottom:-4px;height:3px;border-radius:999px;background:var(--v31-brand)}.v31-count{min-width:21px;height:21px;padding:0 6px;border-radius:999px;background:#f0edef;color:var(--v31-muted);display:grid;place-items:center;font-size:11px;font-weight:750}.v31-tab.is-active .v31-count{background:var(--v31-brand-soft);color:var(--v31-brand)}.v31-panel{display:none}.v31-panel.is-active{display:block}
.v31-order{margin-top:14px;padding:22px 18px 16px}.v31-order-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.v31-order-code{font-size:20px;font-weight:820;letter-spacing:-.03em}.v31-status{padding:7px 12px;border-radius:999px;font-size:11px;font-weight:820;letter-spacing:.04em;background:var(--v31-green-soft);color:var(--v31-green)}.v31-status.is-cancelled{background:var(--v31-red-soft);color:var(--v31-red)}.v31-status.is-complete{background:#f1f1f3;color:#6f6f74}.v31-order-desc{margin-top:15px;font-size:15px;line-height:1.45;font-weight:570;color:#4f4f53}.v31-order-date{margin-top:10px;display:flex;align-items:center;gap:8px;color:var(--v31-muted);font-size:14px}.v31-order-date i{color:var(--v31-brand)}.v31-divider{height:1px;background:var(--v31-line);margin:17px 0}.v31-finance{display:grid;grid-template-columns:minmax(128px,.82fr) 1.35fr;gap:19px;align-items:start}.v31-finance-left{padding-right:18px;border-right:1px solid var(--v31-line)}.v31-finance-label{font-size:12px;color:var(--v31-muted);font-weight:650;margin-bottom:6px}.v31-total{font-size:30px;font-weight:830;letter-spacing:-.055em;white-space:nowrap}.v31-paid-head{display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:12px;color:#4f4f53}.v31-paid-head strong{font-weight:730}.v31-progress{height:8px;background:#e6e4e5;border-radius:999px;margin-top:10px;overflow:hidden}.v31-progress span{display:block;height:100%;background:var(--v31-brand);border-radius:inherit}.v31-balance-label{font-size:12px;color:var(--v31-brand);font-weight:650;margin-top:15px}.v31-balance{font-size:23px;color:var(--v31-brand);font-weight:820;letter-spacing:-.04em;margin-top:3px}
.v31-payments{margin-top:18px;border:1px solid var(--v31-line);border-radius:19px;overflow:hidden;background:#fffaf9}.v31-payments-toggle{width:100%;height:50px;border:0;background:transparent;color:var(--v31-brand);padding:0 14px;display:flex;align-items:center;justify-content:space-between;font-size:15px;font-weight:760}.v31-payments-body{border-top:1px solid var(--v31-line);background:#fff;overflow:hidden;max-height:520px;opacity:1;transition:max-height .28s ease,opacity .18s ease}.v31-payments.is-collapsed .v31-payments-body{max-height:0;opacity:0}.v31-payments-chevron{transition:transform .22s ease}.v31-payments.is-collapsed .v31-payments-chevron{transform:rotate(180deg)}.v31-payment-row{display:grid;grid-template-columns:38px minmax(0,1fr) auto;gap:10px;align-items:center;min-height:68px;padding:10px 13px;border-bottom:1px solid var(--v31-line)}.v31-payment-icon{width:36px;height:36px;border-radius:12px;background:var(--v31-gold-soft);color:var(--v31-gold);display:grid;place-items:center;font-size:14px}.v31-payment-name{font-size:14px;font-weight:660}.v31-payment-date{font-size:11px;color:var(--v31-muted);margin-top:4px}.v31-payment-right{text-align:right}.v31-payment-amount{font-size:15px;font-weight:740;white-space:nowrap}.v31-receipt{border:0;background:transparent;color:var(--v31-brand);font-size:11px;font-weight:720;margin-top:5px;padding:0}.v31-payment-state{display:inline-block;margin-left:5px;padding:2px 6px;border-radius:999px;background:#f2f2f4;color:#777;font-size:9px;font-weight:760}.v31-payment-total{min-height:52px;padding:0 14px;display:flex;align-items:center;justify-content:space-between;color:var(--v31-muted);font-size:13px}.v31-payment-total strong{color:var(--v31-ink);font-size:16px}.v31-view-op{width:100%;height:52px;border:0;border-top:1px solid var(--v31-line);display:flex;align-items:center;justify-content:center;gap:9px;color:var(--v31-brand);font-size:15px;font-weight:750;background:#fff}
.v31-quote{margin-top:14px;padding:20px 18px}.v31-quote-total{margin-top:15px;padding-top:15px;border-top:1px solid var(--v31-line);display:flex;align-items:end;justify-content:space-between;gap:12px}.v31-quote-value{font-size:24px;font-weight:820;letter-spacing:-.04em}.v31-quote-actions{display:flex;gap:8px}.v31-small-btn{height:40px;border:0;border-radius:13px;padding:0 13px;background:var(--v31-brand-soft);color:var(--v31-brand);font-size:13px;font-weight:740;text-decoration:none;display:inline-flex;align-items:center;gap:7px}.v31-empty{margin-top:14px;padding:28px 20px;text-align:center;color:var(--v31-muted)}
.v31-menu{position:fixed;inset:0;background:rgba(0,0,0,.16);z-index:10020;display:none;align-items:flex-end;padding:12px}.v31-menu.is-open{display:flex}.v31-sheet{width:min(100%,520px);margin:0 auto;background:#f7f6f7;border-radius:24px;padding:9px;box-shadow:0 30px 80px rgba(0,0,0,.24)}.v31-sheet button{width:100%;height:52px;border:0;border-bottom:1px solid var(--v31-line);background:#fff;font-size:16px;font-weight:650;display:flex;align-items:center;justify-content:center;gap:9px}.v31-sheet button:first-child{border-radius:17px 17px 0 0}.v31-sheet button:nth-child(3){border-radius:0 0 17px 17px;border-bottom:0}.v31-sheet .v31-cancel{margin-top:9px;border-radius:17px!important;border:0;color:var(--v31-brand);font-weight:760}.v31-toast{position:fixed;left:50%;bottom:calc(22px + env(safe-area-inset-bottom,0px));transform:translate(-50%,12px);background:rgba(25,25,27,.93);color:#fff;padding:10px 15px;border-radius:999px;font-size:13px;font-weight:680;opacity:0;pointer-events:none;transition:.18s;z-index:10030;white-space:nowrap}.v31-toast.is-showing{opacity:1;transform:translate(-50%,0)}
@media(max-width:430px){.v31-header-inner{grid-template-columns:44px 1fr auto}.v31-new-search{padding:0 12px;font-size:12.5px}.v31-title{font-size:19px}.v31-title img{width:18px}.v31-name{font-size:25px}.v31-identity{grid-template-columns:74px minmax(0,1fr) 40px;gap:12px}.v31-avatar{width:74px;height:74px;font-size:33px}.v31-contact-grid{grid-template-columns:1fr}.v31-contact-item:nth-child(2){padding-left:0;border-left:0;border-top:1px solid var(--v31-line)}.v31-summary{grid-template-columns:40px 1fr;padding-left:12px;padding-right:12px}.v31-summary-icon{width:37px;height:37px}.v31-summary-text{font-size:13.5px;gap:6px}.v31-finance{grid-template-columns:1fr 1.08fr;gap:13px}.v31-finance-left{padding-right:12px}.v31-total{font-size:27px}.v31-balance{font-size:21px}}
@media(max-width:350px){.v31-finance{grid-template-columns:1fr}.v31-finance-left{border-right:0;border-bottom:1px solid var(--v31-line);padding:0 0 14px}.v31-header-inner{grid-template-columns:42px 1fr}.v31-new-search{grid-column:1/-1;width:100%;height:40px}.v31-title{justify-content:flex-start}.v31-payment-row{grid-template-columns:36px 1fr}.v31-payment-right{grid-column:2;text-align:left}}
</style>
'''

JS = r'''
<script id="clientes-connected-v31-script">
(function(){
'use strict';
const rootId='clientes-v31-connected';const originalFetch=window.fetch.bind(window);let toastTimer=null;
const clean=v=>String(v??'').trim();const number=v=>{const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};const money=v=>'$'+Math.round(number(v)).toLocaleString('es-CO');const el=(tag,c,t)=>{const n=document.createElement(tag);if(c)n.className=c;if(t!==undefined)n.textContent=t;return n};const icon=c=>{const n=document.createElement('i');n.className=c;n.setAttribute('aria-hidden','true');return n};const validEmail=v=>{const s=clean(v);return !s||/sincorreo|no registrado/i.test(s)?'Sin correo registrado':s};const digits=v=>{let d=clean(v).replace(/\D/g,'');if(d.length===10&&d.startsWith('3'))d='57'+d;return d};const initials=n=>clean(n).split(/\s+/).filter(Boolean).slice(0,1).map(x=>x[0]).join('').toUpperCase()||'C';const dateText=v=>{const s=clean(v);if(!s)return'Sin fecha';if(/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('es-CO',{day:'numeric',month:'short',year:'numeric'})};const orderNumber=i=>clean(i?.numero_op||i?.numero||i?.numero_orden||'S/N');const quoteNumber=i=>clean(i?.numero_cotizacion||i?.numero||'S/N');const docUrl=i=>clean(i?.pdf_url||i?.url||'');const activeItems=items=>(Array.isArray(items)?items:[]).filter(i=>!/ANUL/i.test(clean(i?.estado)));const root=()=>document.getElementById(rootId);const safeCall=(n,...a)=>typeof window[n]==='function'?window[n](...a):undefined;
function toast(m){let n=document.querySelector('.v31-toast');if(!n){n=el('div','v31-toast');document.body.appendChild(n)}n.textContent=m;n.classList.add('is-showing');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('is-showing'),1500)}
function buildHeader(){const h=el('header','v31-header'),inn=el('div','v31-header-inner'),back=el('button','v31-back');back.type='button';back.append(icon('fa-solid fa-chevron-left'));back.onclick=()=>location.href='index.html';const title=el('div','v31-title'),logo=document.createElement('img');logo.src='triangulogold.png';logo.alt='';title.append(logo,el('span','', 'Clientes'));const s=el('button','v31-new-search','Nueva búsqueda');s.type='button';s.onclick=()=>{safeCall('reiniciarBusqueda');const r=root();if(r){r.className='';r.replaceChildren()}};inn.append(back,title,s);h.append(inn);return h}
function showLoading(){const r=root();if(!r)return;r.className='is-visible';r.replaceChildren();const shell=el('main','v31-shell'),box=el('div','v31-loading');box.append(icon('fa-solid fa-circle-notch fa-spin'),el('div','', 'Consultando cliente…'));shell.append(box);r.append(buildHeader(),shell)}
function showError(m){const r=root();if(!r)return;r.className='is-visible';r.replaceChildren();const shell=el('main','v31-shell');shell.append(el('div','v31-card v31-empty',m||'No fue posible cargar el cliente.'));r.append(buildHeader(),shell)}
function contactText(c){return[clean(c?.nombre),`Cédula: ${clean(c?.cedula)}`,`Teléfono: ${clean(c?.telefono)}`,`Correo: ${validEmail(c?.email)}`,`Dirección: ${clean(c?.direccion)||'Sin dirección registrada'}`].join('\n')}
async function copyText(t){try{if(navigator.clipboard&&isSecureContext)await navigator.clipboard.writeText(t);else{const a=document.createElement('textarea');a.value=t;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}toast('Datos copiados')}catch(e){toast('No se pudo copiar')}}
function openMenu(c){document.querySelector('.v31-menu')?.remove();const menu=el('div','v31-menu is-open'),sheet=el('div','v31-sheet'),edit=el('button','');edit.append(icon('fa-solid fa-pen'),el('span','', 'Editar cliente'));edit.onclick=()=>{menu.remove();safeCall('abrirModalEditar')};const copy=el('button','');copy.append(icon('fa-regular fa-copy'),el('span','', 'Copiar datos'));copy.onclick=()=>{menu.remove();copyText(contactText(c))};const share=el('button','');share.append(icon('fa-solid fa-share-nodes'),el('span','', 'Compartir'));share.onclick=async()=>{menu.remove();const t=contactText(c);if(navigator.share){try{await navigator.share({title:'Cliente HomeEasy',text:t});return}catch(e){if(e?.name==='AbortError')return}}copyText(t)};const cancel=el('button','v31-cancel','Cancelar');cancel.onclick=()=>menu.remove();sheet.append(edit,copy,share,cancel);menu.append(sheet);menu.onclick=e=>{if(e.target===menu)menu.remove()};document.body.append(menu)}
function buildContact(c){const card=el('section','v31-card v31-contact'),identity=el('div','v31-identity'),avatar=el('div','v31-avatar',initials(c?.nombre)),badge=el('span','v31-avatar-badge'),logo=document.createElement('img');logo.src='triangulogold.png';logo.alt='HomeEasy';badge.append(logo);avatar.append(badge);const who=el('div','');who.append(el('h1','v31-name',clean(c?.nombre)||'Cliente'),el('div','v31-id-label','Cédula'),el('div','v31-id',clean(c?.cedula)||'Sin identificación'));const more=el('button','v31-more');more.type='button';more.append(icon('fa-solid fa-ellipsis'));more.onclick=()=>openMenu(c);identity.append(avatar,who,more);card.append(identity);const grid=el('div','v31-contact-grid'),phone=el('a','v31-contact-item'),pd=digits(c?.telefono);phone.href=pd?'tel:+'+pd:'#';const pi=el('div','v31-contact-icon');pi.append(icon('fa-solid fa-phone'));const pt=el('div','');pt.append(el('div','v31-contact-label','Teléfono'),el('div','v31-contact-value',clean(c?.telefono)||'No registrado'));phone.append(pi,pt);const addr=el('div','v31-contact-item'),ai=el('div','v31-contact-icon');ai.append(icon('fa-solid fa-location-dot'));const at=el('div','');at.append(el('div','v31-contact-label','Dirección'),el('div','v31-contact-value',clean(c?.direccion)||'Sin dirección registrada'));addr.append(ai,at);grid.append(phone,addr);card.append(grid);const email=el('div','v31-email'),ei=el('div','v31-contact-icon');ei.append(icon('fa-regular fa-envelope'));email.append(ei,el('span','',validEmail(c?.email)));card.append(email);const actions=el('div','v31-contact-actions'),wa=el('button','v31-whatsapp');wa.type='button';wa.append(icon('fa-brands fa-whatsapp'),el('span','', 'WhatsApp'));wa.onclick=()=>pd?window.open('https://wa.me/'+pd,'_blank','noopener,noreferrer'):toast('Sin teléfono válido');const mb=el('button','v31-more-bottom');mb.type='button';mb.append(icon('fa-solid fa-ellipsis'));mb.onclick=()=>openMenu(c);actions.append(wa,mb);card.append(actions);return card}
function buildSummary(o){const valid=activeItems(o),total=valid.reduce((s,x)=>s+Math.max(0,number(x?.total)),0),pending=valid.reduce((s,x)=>s+Math.max(0,number(x?.saldo)),0),sec=el('section','v31-summary'),ico=el('div','v31-summary-icon');ico.append(icon('fa-solid fa-bag-shopping'));const text=el('div','v31-summary-text'),b=el('span','');b.append(document.createTextNode('Comprado '),el('strong','',money(total)));const p=el('span','');p.append(document.createTextNode('Pendiente '),el('span','pending',money(pending)));text.append(b,el('span','v31-dot','•'),p);sec.append(ico,text);return sec}
function statusClass(s){s=clean(s).toUpperCase();if(/ANUL/.test(s))return' is-cancelled';if(/COMPLET|PAGAD|CERRAD|ENTREGAD/.test(s))return' is-complete';return''}function paymentLabel(p){if(clean(p?.recibo).toUpperCase()==='INICIAL')return'Abono inicial';if(clean(p?.tipoRegistro).toUpperCase()==='TRASLADO_CREDITO')return'Traslado de crédito';return clean(p?.tipo||p?.metodo||p?.forma_pago||'Abono')}function paymentIcon(p){if(clean(p?.recibo).toUpperCase()==='INICIAL')return'fa-solid fa-receipt';if(clean(p?.tipoRegistro).toUpperCase()==='TRASLADO_CREDITO')return'fa-solid fa-arrow-right-arrow-left';return'fa-solid fa-building-columns'}
function buildPayments(item,index){const details=Array.isArray(item?.abonos_detalle)?item.abonos_detalle:[],total=Math.max(0,number(item?.total)),saldo=Math.max(0,number(item?.saldo)),paid=Math.max(0,total-saldo),wrap=el('div','v31-payments'+((index===0&&details.length<=3)?'':' is-collapsed')),toggle=el('button','v31-payments-toggle');toggle.type='button';toggle.append(el('span','',details.length?`${details.length} ${details.length===1?'abono':'abonos'}`:'Abonos'),icon('fa-solid fa-chevron-up v31-payments-chevron'));const body=el('div','v31-payments-body');if(details.length)details.forEach(p=>{const row=el('div','v31-payment-row'),ic=el('div','v31-payment-icon');ic.append(icon(paymentIcon(p)));const mid=el('div',''),name=el('div','v31-payment-name',paymentLabel(p)),state=clean(p?.estado);if(state&&!/ACTIVO|SIN_PAGO/i.test(state))name.append(el('span','v31-payment-state',state.replace(/_/g,' ')));mid.append(name,el('div','v31-payment-date',dateText(p?.fecha)));const right=el('div','v31-payment-right');right.append(el('div','v31-payment-amount',money(p?.valor)));if(clean(p?.url)&&clean(p?.recibo).toUpperCase()!=='INICIAL'){const rec=el('button','v31-receipt');rec.type='button';rec.append(document.createTextNode('Ver recibo '),icon('fa-solid fa-chevron-right'));rec.onclick=e=>{e.stopPropagation();safeCall('abrirVisorPDF',p.url)};right.append(rec)}row.append(ic,mid,right);body.append(row)});else body.append(el('div','v31-empty',paid>0?'El total abonado está registrado, sin recibos detallados.':'No hay abonos registrados.'));const tr=el('div','v31-payment-total');tr.append(el('span','', 'Total abonado'),el('strong','',money(paid)));body.append(tr);const url=docUrl(item);if(url){const v=el('button','v31-view-op');v.type='button';v.append(icon('fa-regular fa-file-pdf'),el('span','', 'Ver OP'),icon('fa-solid fa-chevron-right'));v.onclick=()=>safeCall('abrirVisorPDF',url);body.append(v)}wrap.append(toggle,body);toggle.onclick=()=>wrap.classList.toggle('is-collapsed');return wrap}
function buildOrder(item,index){const card=el('article','v31-card v31-order'),head=el('div','v31-order-head');head.append(el('div','v31-order-code','OP '+orderNumber(item)),el('span','v31-status'+statusClass(item?.estado),clean(item?.estado||'REGISTRADO').toUpperCase()));card.append(head,el('div','v31-order-desc',clean(item?.detalle||item?.descripcion)||'Sin detalles'));const date=el('div','v31-order-date');date.append(icon('fa-regular fa-calendar-days'),el('span','',dateText(item?.fecha)));card.append(date,el('div','v31-divider'));const total=Math.max(0,number(item?.total)),saldo=Math.max(0,number(item?.saldo)),cancel=/ANUL/i.test(clean(item?.estado)),paid=cancel?0:Math.max(0,total-saldo),pct=total>0?Math.max(0,Math.min(100,Math.round(paid/total*100))):0,finance=el('div','v31-finance'),left=el('div','v31-finance-left');left.append(el('div','v31-finance-label','Total'),el('div','v31-total',money(total)));const right=el('div',''),ph=el('div','v31-paid-head');ph.append(el('strong','',`Abonado ${money(paid)}`),el('span','',pct+'%'));const progress=el('div','v31-progress'),bar=el('span','');bar.style.width=pct+'%';progress.append(bar);right.append(ph,progress,el('div','v31-balance-label','Saldo'),el('div','v31-balance',cancel?'Orden anulada':money(saldo)));finance.append(left,right);card.append(finance,buildPayments(item,index));return card}
function buildQuote(item){const card=el('article','v31-card v31-quote'),head=el('div','v31-order-head');head.append(el('div','v31-order-code','COT '+quoteNumber(item)),el('span','v31-status'+statusClass(item?.estado),clean(item?.estado||'REGISTRADA').toUpperCase()));card.append(head,el('div','v31-order-desc',clean(item?.detalle||item?.descripcion)||'Sin detalles'));const date=el('div','v31-order-date');date.append(icon('fa-regular fa-calendar-days'),el('span','',dateText(item?.fecha)));card.append(date);const bottom=el('div','v31-quote-total'),amount=el('div','');amount.append(el('div','v31-finance-label','Valor'),el('div','v31-quote-value',money(item?.total)));const actions=el('div','v31-quote-actions'),url=docUrl(item);if(url){const pdf=el('button','v31-small-btn');pdf.type='button';pdf.append(icon('fa-regular fa-file-pdf'),el('span','', 'Ver PDF'));pdf.onclick=()=>safeCall('abrirVisorPDF',url);actions.append(pdf)}const state=clean(item?.estado).toUpperCase();if(!/CONVERTIDA|ANUL/.test(state)){const link=document.createElement('a');link.className='v31-small-btn';link.href='pedido.html?cotizacion='+encodeURIComponent(quoteNumber(item));link.append(icon('fa-solid fa-arrow-right-arrow-left'),el('span','', 'A OP'));actions.append(link)}bottom.append(amount,actions);card.append(bottom);return card}
function render(data){const r=root();if(!r)return;const c=data?.cliente||{},orders=Array.isArray(data?.ordenes)?data.ordenes:[],quotes=Array.isArray(data?.cotizaciones)?data.cotizaciones:[];r.className='is-visible';r.replaceChildren();const shell=el('main','v31-shell');shell.append(buildContact(c),buildSummary(orders));const tabs=el('div','v31-tabs'),bo=el('button','v31-tab is-active'),bq=el('button','v31-tab');bo.type=bq.type='button';bo.append(el('span','', 'Órdenes'),el('span','v31-count',String(orders.length)));bq.append(el('span','', 'Cotizaciones'),el('span','v31-count',String(quotes.length)));tabs.append(bo,bq);shell.append(tabs);const op=el('section','v31-panel is-active'),qp=el('section','v31-panel');if(orders.length)orders.forEach((x,i)=>op.append(buildOrder(x,i)));else op.append(el('div','v31-card v31-empty','Sin órdenes registradas.'));if(quotes.length)quotes.forEach(x=>qp.append(buildQuote(x)));else qp.append(el('div','v31-card v31-empty','Sin cotizaciones registradas.'));bo.onclick=()=>{bo.classList.add('is-active');bq.classList.remove('is-active');op.classList.add('is-active');qp.classList.remove('is-active')};bq.onclick=()=>{bq.classList.add('is-active');bo.classList.remove('is-active');qp.classList.add('is-active');op.classList.remove('is-active')};shell.append(op,qp);r.append(buildHeader(),shell)}
window.fetch=async function(input,init){const url=typeof input==='string'?input:(input&&input.url)||'',hist=/[?&]tipo=HISTORIAL_CLIENTE(?:&|$)/i.test(url);if(hist)showLoading();try{const response=await originalFetch(input,init);if(hist)response.clone().json().then(d=>d&&d.status==='found'?render(d):showError('Cliente no encontrado.')).catch(()=>showError('No fue posible interpretar la respuesta del cliente.'));return response}catch(e){if(hist)showError('Error de conexión al consultar el cliente.');throw e}};
window.addEventListener('DOMContentLoaded',()=>document.body.classList.add('clientes-connected-v31'),{once:true});
})();
</script>
'''

source = source.replace('</head>', CSS + JS + '\n</head>', 1)
OUTPUT.write_text(source, encoding="utf-8", newline="\n")

checks = {
    "output": OUTPUT.exists() and OUTPUT.stat().st_size > 90000,
    "same search": "Hommybuscando.png" in source and "Buscar Cliente" in source,
    "real history endpoint": "HISTORIAL_CLIENTE" in source,
    "real client list": "listaClientes=1" in source,
    "protected preview permission": "'clientes-conectado-v31.html': 'clientes.read'" in source,
    "inline guard": 'id="clientes-v31-inline-guard"' in source,
    "brand color": "#B2566C" in source,
    "real icons": "fa-solid fa-phone" in source and "fa-location-dot" in source and "fa-regular fa-envelope" in source,
    "real logo": "triangulogold.png" in source,
    "orders": "buildOrder" in source,
    "quotes": "buildQuote" in source,
    "payments": "buildPayments" in source and "abonos_detalle" in source,
    "pdf": "abrirVisorPDF" in source,
    "edit": "abrirModalEditar" in source,
    "self search path": "window.location.pathname + '?search='" in source,
}
failed = [name for name, ok in checks.items() if not ok]
if failed: raise SystemExit("Contratos fallidos: " + ", ".join(failed))
print(f"Generado {OUTPUT.name}: {OUTPUT.stat().st_size} bytes")
for name in checks: print("OK", name)
