from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "clientes.html"
GUARD = ROOT / "homeeasy-page-guard.js"
OUTPUT = ROOT / "clientes-conectado-v31.html"

source = SOURCE.read_text(encoding="utf-8")
guard = GUARD.read_text(encoding="utf-8")

required_source_markers = [
    "#pantalla-inicio", "#pantalla-resultados", "function abrirVisorPDF", "function cerrarVisorPDF",
    "function abrirModalEditar", "function guardarEdicionCliente", "function confirmarEdicion",
    "function confirmarAnulacion", "function analizarAnulacion", "function ejecutarAnulacionSegura",
    "ANALIZAR_ANULACION_DOCUMENTO", "EJECUTAR_ANULACION_SEGURA", "HISTORIAL_CLIENTE",
    "listaClientes=1", "pedido.html?cotizacion=",
]
missing = [m for m in required_source_markers if m not in source]
if missing:
    raise SystemExit("clientes.html perdió funciones heredadas: " + ", ".join(missing))
if "'clientes.html': 'clientes.read'" not in guard:
    raise SystemExit("No se encontró el permiso clientes.read en el guard")

source = source.replace(
    'content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover"',
    'content="width=device-width, initial-scale=1.0, viewport-fit=cover"', 1)

guard = guard.replace("'clientes.html': 'clientes.read',",
    "'clientes.html': 'clientes.read',\n        'clientes-conectado-v31.html': 'clientes.read',", 1)
external_guard = '<script src="homeeasy-page-guard.js?v=3.6"></script>'
if external_guard not in source:
    raise SystemExit("No se encontró la referencia al guard 3.6")
source = source.replace(external_guard, '<script id="clientes-v31-inline-guard">\n' + guard + '\n</script>', 1)
source = source.replace("window.history.replaceState({}, '', `clientes.html?search=${cedula}`);",
    "window.history.replaceState({}, '', window.location.pathname + '?search=' + encodeURIComponent(cedula));")
source = source.replace("window.history.replaceState({}, '', 'clientes.html');",
    "window.history.replaceState({}, '', window.location.pathname);")
source = source.replace(
    "const drop = document.getElementById(id);\n            drop.style.display = drop.style.display === 'flex' ? 'none' : 'flex';",
    "const drop = document.getElementById(id);\n            if (!drop) return;\n            drop.style.display = drop.style.display === 'flex' ? 'none' : 'flex';", 1)
source = source.replace('<body>', '<body class="clientes-connected-v31">', 1)
preview_root = '\n        <div id="clientes-v31-connected" aria-live="polite"></div>\n'
marker = '        <div class="container">'
if marker not in source:
    raise SystemExit("No se encontró el contenedor legado de resultados")
source = source.replace(marker, preview_root + marker, 1)

CSS = r'''
<style id="clientes-connected-v31-style">
body.clientes-connected-v31{--v31-brand:#B2566C;--v31-brand-dark:#95485b;--v31-brand-soft:#f8eef1;--v31-gold:#c2a468;--v31-gold-soft:#fbf5e8;--v31-ink:#202024;--v31-muted:#77777d;--v31-line:#e9e7e8;--v31-bg:#f6f6f7;--v31-card:#fff;--v31-green:#24745d;--v31-green-soft:#eaf6f0;--v31-red:#b13e4f;--v31-red-soft:#fff0f2;--v31-shadow:0 12px 34px rgba(42,31,35,.045)}
body.clientes-connected-v31 #pantalla-resultados{padding:0!important;min-height:100dvh!important;background:var(--v31-bg)!important}
body.clientes-connected-v31 #pantalla-resultados>.header-mini,body.clientes-connected-v31 #pantalla-resultados>.container{display:none!important}
#clientes-v31-connected{display:none;min-height:100dvh;background:var(--v31-bg);padding-bottom:calc(36px + env(safe-area-inset-bottom,0px));color:var(--v31-ink)}
#clientes-v31-connected.is-visible{display:block}#clientes-v31-connected *{box-sizing:border-box}#clientes-v31-connected button{font:inherit}
#clientes-v31-connected button:focus-visible,#clientes-v31-connected a:focus-visible{outline:3px solid rgba(178,86,108,.22);outline-offset:3px}
.v31-header{position:sticky;top:0;z-index:30;background:rgba(246,246,247,.92);-webkit-backdrop-filter:blur(22px) saturate(150%);backdrop-filter:blur(22px) saturate(150%);border-bottom:1px solid rgba(60,60,67,.07)}
.v31-header-inner{width:calc(100% - 40px);margin:0 auto;min-height:78px;padding:calc(8px + env(safe-area-inset-top,0px)) 0 8px;display:grid;grid-template-columns:46px 1fr auto;align-items:center;gap:12px}
.v31-back{width:44px;height:44px;border:1px solid rgba(60,60,67,.07);border-radius:50%;background:#fff;color:var(--v31-brand);box-shadow:0 6px 18px rgba(0,0,0,.045);display:grid;place-items:center;font-size:17px;transition:.18s ease}.v31-back:hover{background:var(--v31-brand-soft);transform:translateY(-1px)}
.v31-title{display:flex;align-items:center;justify-content:center;gap:9px;font-size:20px;font-weight:680;letter-spacing:-.025em;white-space:nowrap}.v31-title img{width:22px;height:auto;display:block}
.v31-new-search{height:44px;border-radius:999px;padding:0 18px;border:1.25px solid var(--v31-brand);background:transparent;color:var(--v31-brand);font-size:14px;font-weight:590;white-space:nowrap;cursor:pointer;transition:background .18s ease,color .18s ease,box-shadow .18s ease,transform .18s ease}.v31-new-search:hover{background:var(--v31-brand);color:#fff;box-shadow:0 8px 20px rgba(178,86,108,.18);transform:translateY(-1px)}.v31-new-search:active{transform:translateY(0) scale(.98)}
.v31-shell{width:calc(100% - 40px);margin:18px auto 0}.v31-card{background:var(--v31-card);border:1px solid rgba(60,60,67,.07);border-radius:24px;box-shadow:var(--v31-shadow)}
.v31-loading{margin:36px auto;padding:30px 24px;max-width:380px;text-align:center;background:#fff;border:1px solid var(--v31-line);border-radius:24px;box-shadow:var(--v31-shadow);color:var(--v31-muted)}.v31-loading i{display:block;margin:0 auto 12px;color:var(--v31-brand);font-size:23px}
.v31-contact{padding:24px}.v31-identity{display:grid;grid-template-columns:76px minmax(0,1fr) 42px;gap:15px;align-items:center}.v31-avatar{position:relative;width:76px;height:76px;border-radius:50%;background:linear-gradient(145deg,#fbf6f6,#f4e8ec);display:grid;place-items:center;color:var(--v31-brand);font-size:34px;font-weight:650;letter-spacing:-.03em}.v31-avatar-badge{position:absolute;right:-3px;bottom:3px;width:27px;height:27px;border-radius:50%;background:#fff;box-shadow:0 5px 14px rgba(0,0,0,.09);display:grid;place-items:center}.v31-avatar-badge img{width:17px;height:auto}.v31-name{font-size:26px;font-weight:700;letter-spacing:-.035em;line-height:1.08;margin:0;overflow-wrap:anywhere}.v31-id-label{margin-top:8px;color:var(--v31-muted);font-size:12px;font-weight:520}.v31-id{margin-top:2px;font-size:16px;font-weight:560}
.v31-more,.v31-more-bottom,.v31-doc-more{border:1px solid var(--v31-line);background:#fff;color:var(--v31-brand);display:grid;place-items:center;cursor:pointer;transition:.16s ease}.v31-more{width:40px;height:40px;border-radius:50%;font-size:16px}.v31-more:hover,.v31-more-bottom:hover,.v31-doc-more:hover{background:var(--v31-brand-soft);border-color:#ead7dc}
.v31-contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:0;margin-top:20px}.v31-contact-item{min-height:72px;display:grid;grid-template-columns:43px minmax(0,1fr);gap:12px;align-items:center;padding:7px 16px 7px 0;text-decoration:none;color:inherit}.v31-contact-item:nth-child(2){padding-left:18px;border-left:1px solid var(--v31-line)}.v31-contact-icon{width:40px;height:40px;border-radius:50%;background:var(--v31-brand-soft);color:var(--v31-brand);display:grid;place-items:center;font-size:16px}.v31-contact-label{font-size:12px;color:var(--v31-muted);font-weight:500;margin-bottom:4px}.v31-contact-value{font-size:15px;font-weight:560;letter-spacing:-.01em;line-height:1.3;overflow-wrap:anywhere}.v31-email{margin-top:3px;min-height:57px;display:flex;align-items:center;gap:12px;color:var(--v31-muted);border-bottom:1px solid var(--v31-line);padding:3px 0 14px;font-size:14px}.v31-email .v31-contact-icon{flex:0 0 auto;background:#f5f4f5;color:#929096}
.v31-contact-actions{display:grid;grid-template-columns:1fr 52px;gap:12px;margin-top:17px}.v31-whatsapp{height:50px;border:0;border-radius:16px;background:var(--v31-brand);color:#fff;font-size:16px;font-weight:620;display:flex;align-items:center;justify-content:center;gap:10px;box-shadow:0 9px 22px rgba(178,86,108,.17);cursor:pointer;transition:.18s ease}.v31-whatsapp i{font-size:20px}.v31-whatsapp:hover{background:var(--v31-brand-dark);transform:translateY(-1px)}.v31-more-bottom{height:50px;border-radius:50%;font-size:17px}
.v31-summary{margin-top:14px;background:#fff;border:1px solid rgba(60,60,67,.07);border-radius:20px;min-height:66px;box-shadow:0 10px 26px rgba(28,24,23,.035);display:grid;grid-template-columns:42px 1fr;align-items:center;padding:10px 16px}.v31-summary-icon{width:38px;height:38px;border-radius:50%;background:var(--v31-gold-soft);color:var(--v31-gold);display:grid;place-items:center;font-size:15px}.v31-summary-text{display:flex;align-items:center;justify-content:center;gap:9px;flex-wrap:wrap;font-size:14px;line-height:1.3}.v31-summary-text strong{font-weight:650}.v31-summary-text .pending{color:var(--v31-brand);font-weight:650}.v31-dot{color:var(--v31-gold);font-weight:800}
.v31-tabs{margin-top:16px;background:#eae9eb;border-radius:17px;padding:3px;display:grid;grid-template-columns:1fr 1fr}.v31-tab{height:46px;border:0;border-radius:14px;background:transparent;color:#77777c;font-size:15px;font-weight:560;position:relative;display:flex;align-items:center;justify-content:center;gap:7px;cursor:pointer}.v31-tab.is-active{background:#fff;color:var(--v31-brand);box-shadow:0 3px 12px rgba(0,0,0,.045)}.v31-tab.is-active:after{content:"";position:absolute;left:18%;right:18%;bottom:-4px;height:3px;border-radius:999px;background:var(--v31-brand)}.v31-count{min-width:21px;height:21px;padding:0 6px;border-radius:999px;background:#f0edef;color:var(--v31-muted);display:grid;place-items:center;font-size:11px;font-weight:650}.v31-tab.is-active .v31-count{background:var(--v31-brand-soft);color:var(--v31-brand)}.v31-panel{display:none}.v31-panel.is-active{display:block}
.v31-order{position:relative;margin-top:14px;padding:22px 22px 18px;overflow:visible}.v31-order:before{content:"";position:absolute;left:0;top:24px;bottom:24px;width:3px;border-radius:0 3px 3px 0;background:linear-gradient(var(--v31-brand),var(--v31-gold));opacity:.7}.v31-order-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.v31-order-code{font-size:20px;font-weight:700;letter-spacing:-.025em}.v31-order-head-actions{display:flex;align-items:center;gap:8px;position:relative}.v31-status{padding:7px 12px;border-radius:999px;font-size:11px;font-weight:700;letter-spacing:.035em;background:var(--v31-green-soft);color:var(--v31-green)}.v31-status.is-cancelled{background:var(--v31-red-soft);color:var(--v31-red)}.v31-status.is-complete{background:#f1f1f3;color:#6f6f74}.v31-doc-more{width:36px;height:36px;border-radius:50%;font-size:15px}
.v31-doc-popover{position:absolute;right:0;top:43px;z-index:60;width:210px;padding:6px;background:#fff;border:1px solid var(--v31-line);border-radius:15px;box-shadow:0 16px 42px rgba(32,27,29,.16);display:none}.v31-doc-popover.is-open{display:block;animation:v31pop .14s ease-out}@keyframes v31pop{from{opacity:0;transform:translateY(-4px) scale(.98)}to{opacity:1;transform:none}}.v31-doc-option{width:100%;height:44px;border:0;border-radius:11px;background:#fff;color:var(--v31-ink);display:flex;align-items:center;gap:10px;padding:0 12px;font-size:13px;font-weight:560;text-align:left;cursor:pointer}.v31-doc-option:hover{background:#f7f5f6}.v31-doc-option i{width:17px;color:var(--v31-brand)}.v31-doc-option.is-danger{color:#a43c4a}.v31-doc-option.is-danger i{color:#a43c4a}
.v31-order-layout{display:grid;grid-template-columns:minmax(280px,.9fr) minmax(460px,1.1fr);gap:34px;align-items:center;margin-top:16px}.v31-order-intro{min-width:0}.v31-order-desc{font-size:15px;line-height:1.5;font-weight:480;color:#525258}.v31-order-date{margin-top:11px;display:flex;align-items:center;gap:8px;color:var(--v31-muted);font-size:13px;font-weight:470}.v31-order-date i{color:var(--v31-brand)}
.v31-finance{display:grid;grid-template-columns:minmax(150px,.72fr) minmax(260px,1.28fr);gap:22px;align-items:start}.v31-finance-left{padding-right:22px;border-right:1px solid var(--v31-line)}.v31-finance-label{font-size:12px;color:var(--v31-muted);font-weight:520;margin-bottom:6px}.v31-total{font-size:clamp(28px,2.15vw,37px);font-weight:700;letter-spacing:-.045em;white-space:nowrap}.v31-paid-head{display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:12px;color:#55555a}.v31-paid-head strong{font-weight:600}.v31-progress{height:7px;background:#e6e4e5;border-radius:999px;margin-top:10px;overflow:hidden}.v31-progress span{display:block;height:100%;background:var(--v31-brand);border-radius:inherit}.v31-balance-label{font-size:12px;color:var(--v31-brand);font-weight:560;margin-top:14px}.v31-balance{font-size:clamp(22px,1.65vw,29px);color:var(--v31-brand);font-weight:680;letter-spacing:-.035em;margin-top:3px}
.v31-order-actions{display:grid;grid-template-columns:minmax(0,1fr) minmax(160px,230px);gap:10px;margin-top:20px;padding-top:17px;border-top:1px solid var(--v31-line)}.v31-history-toggle,.v31-view-op{height:48px;border-radius:14px;display:flex;align-items:center;justify-content:center;gap:9px;font-size:14px;font-weight:590;cursor:pointer;transition:.16s ease}.v31-history-toggle{border:1px solid #eadde0;background:#fffafa;color:var(--v31-brand)}.v31-history-toggle:hover{background:var(--v31-brand-soft);border-color:#dfc8ce}.v31-history-toggle .v31-history-count{min-width:22px;height:22px;padding:0 7px;border-radius:999px;background:#fff;color:var(--v31-brand);border:1px solid #eadde0;display:grid;place-items:center;font-size:11px;font-weight:650}.v31-history-chevron{transition:transform .2s ease}.v31-history-toggle[aria-expanded="true"] .v31-history-chevron{transform:rotate(180deg)}.v31-view-op{border:1px solid var(--v31-brand);background:var(--v31-brand);color:#fff}.v31-view-op:hover{background:var(--v31-brand-dark);border-color:var(--v31-brand-dark);box-shadow:0 7px 18px rgba(178,86,108,.15)}.v31-view-op:disabled{cursor:not-allowed;opacity:.42;box-shadow:none}
.v31-history-panel{overflow:hidden;max-height:0;opacity:0;transition:max-height .28s ease,opacity .18s ease;margin-top:0}.v31-history-panel.is-open{max-height:760px;opacity:1;margin-top:12px}.v31-history-box{border:1px solid var(--v31-line);border-radius:17px;overflow:hidden;background:#fff}.v31-history-title{height:47px;padding:0 15px;display:flex;align-items:center;gap:8px;border-bottom:1px solid var(--v31-line);background:#fbfafb;color:#5c585b;font-size:13px;font-weight:600}
.v31-payment-row{display:grid;grid-template-columns:minmax(240px,1.15fr) minmax(130px,.65fr) minmax(145px,.55fr);gap:14px;align-items:center;min-height:62px;padding:9px 15px;border-bottom:1px solid var(--v31-line);background:#fff}.v31-payment-row.is-clickable{cursor:pointer;transition:background .14s ease}.v31-payment-row.is-clickable:hover{background:#faf7f8}.v31-payment-left{display:flex;align-items:center;gap:10px;min-width:0}.v31-payment-icon{width:34px;height:34px;flex:0 0 34px;border-radius:10px;background:var(--v31-gold-soft);color:var(--v31-gold);display:grid;place-items:center;font-size:13px}.v31-payment-name{font-size:14px;font-weight:560;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v31-payment-eye{margin-left:4px;color:var(--v31-brand);font-size:13px}.v31-payment-state{display:inline-block;margin-left:6px;padding:2px 6px;border-radius:999px;background:#f2f2f4;color:#707076;font-size:9px;font-weight:650;vertical-align:middle}.v31-payment-state.is-transfer{background:#eef6ff;color:#2371b7}.v31-payment-date{text-align:center;color:#64646a;font-size:13px;font-weight:480}.v31-payment-amount{text-align:right;font-size:14px;font-weight:650;white-space:nowrap}.v31-payment-total{min-height:49px;padding:0 15px;display:flex;align-items:center;justify-content:space-between;color:var(--v31-muted);font-size:13px;background:#fbfbfc}.v31-payment-total strong{color:var(--v31-ink);font-size:15px;font-weight:650}.v31-empty-history{padding:24px;text-align:center;color:var(--v31-muted);font-size:13px}
.v31-quote{position:relative;margin-top:14px;padding:21px 22px}.v31-quote-total{margin-top:15px;padding-top:15px;border-top:1px solid var(--v31-line);display:flex;align-items:end;justify-content:space-between;gap:12px}.v31-quote-value{font-size:24px;font-weight:680;letter-spacing:-.035em}.v31-quote-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.v31-small-btn{height:40px;border:0;border-radius:12px;padding:0 13px;background:var(--v31-brand-soft);color:var(--v31-brand);font-size:13px;font-weight:590;text-decoration:none;display:inline-flex;align-items:center;gap:7px;cursor:pointer}.v31-small-btn:hover{background:#f0dfe4;color:var(--v31-brand-dark)}.v31-empty{margin-top:14px;padding:28px 20px;text-align:center;color:var(--v31-muted)}
.v31-menu{position:fixed;inset:0;background:rgba(0,0,0,.16);z-index:10020;display:none;align-items:flex-end;padding:12px}.v31-menu.is-open{display:flex}.v31-sheet{width:min(100%,520px);margin:0 auto;background:#f7f6f7;border-radius:24px;padding:9px;box-shadow:0 30px 80px rgba(0,0,0,.24)}.v31-sheet button{width:100%;height:52px;border:0;border-bottom:1px solid var(--v31-line);background:#fff;font-size:16px;font-weight:560;display:flex;align-items:center;justify-content:center;gap:9px}.v31-sheet button:first-child{border-radius:17px 17px 0 0}.v31-sheet button:nth-child(3){border-radius:0 0 17px 17px;border-bottom:0}.v31-sheet .v31-cancel{margin-top:9px;border-radius:17px!important;border:0;color:var(--v31-brand);font-weight:650}.v31-toast{position:fixed;left:50%;bottom:calc(22px + env(safe-area-inset-bottom,0px));transform:translate(-50%,12px);background:rgba(25,25,27,.93);color:#fff;padding:10px 15px;border-radius:999px;font-size:13px;font-weight:560;opacity:0;pointer-events:none;transition:.18s;z-index:10030;white-space:nowrap}.v31-toast.is-showing{opacity:1;transform:translate(-50%,0)}
@media(min-width:900px){.v31-contact{display:grid;grid-template-columns:minmax(330px,.9fr) minmax(520px,1.35fr) minmax(250px,.65fr);grid-template-areas:"identity contacts actions" "email contacts actions";column-gap:28px;row-gap:4px;align-items:center}.v31-identity{grid-area:identity}.v31-contact-grid{grid-area:contacts;margin-top:0}.v31-email{grid-area:email;border-bottom:0;padding:0;min-height:42px;margin-top:0}.v31-contact-actions{grid-area:actions;margin-top:0;align-self:center}.v31-contact-item{min-height:68px}}
@media(max-width:899px){.v31-header-inner,.v31-shell{width:min(calc(100% - 24px),720px)}.v31-order-layout{grid-template-columns:1fr;gap:18px}.v31-finance{max-width:none}}
@media(max-width:520px){.v31-header-inner{grid-template-columns:42px 1fr auto;gap:8px}.v31-new-search{padding:0 11px;font-size:12.5px}.v31-title{font-size:18px}.v31-title img{width:19px}.v31-contact{padding:20px 18px 17px}.v31-name{font-size:24px}.v31-identity{grid-template-columns:70px minmax(0,1fr) 38px;gap:11px}.v31-avatar{width:70px;height:70px;font-size:31px}.v31-contact-grid{grid-template-columns:1fr}.v31-contact-item:nth-child(2){padding-left:0;border-left:0;border-top:1px solid var(--v31-line)}.v31-summary{grid-template-columns:38px 1fr;padding-left:12px;padding-right:12px}.v31-summary-icon{width:36px;height:36px}.v31-summary-text{font-size:13px;gap:6px}.v31-order{padding:20px 17px 16px}.v31-finance{grid-template-columns:1fr 1.08fr;gap:13px}.v31-finance-left{padding-right:12px}.v31-total{font-size:27px}.v31-balance{font-size:21px}.v31-order-actions{grid-template-columns:1fr 120px}.v31-history-toggle,.v31-view-op{font-size:13px}.v31-payment-row{grid-template-columns:minmax(0,1fr) auto;gap:7px 12px;padding:11px 13px}.v31-payment-left{grid-column:1/-1}.v31-payment-date{text-align:left;padding-left:44px;font-size:12px}.v31-payment-amount{grid-column:2;grid-row:2;font-size:13px}}
@media(max-width:355px){.v31-header-inner{grid-template-columns:40px 1fr}.v31-new-search{grid-column:1/-1;width:100%;height:40px}.v31-title{justify-content:flex-start}.v31-finance{grid-template-columns:1fr}.v31-finance-left{border-right:0;border-bottom:1px solid var(--v31-line);padding:0 0 13px}.v31-order-actions{grid-template-columns:1fr}.v31-view-op{height:44px}}
</style>
'''

JS = r'''
<script id="clientes-connected-v31-script">
(function(){
'use strict';
const rootId='clientes-v31-connected',originalFetch=window.fetch.bind(window);let toastTimer=null;
const clean=v=>String(v??'').trim(),number=v=>{const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0},money=v=>'$'+Math.round(number(v)).toLocaleString('es-CO');
const el=(tag,c,t)=>{const n=document.createElement(tag);if(c)n.className=c;if(t!==undefined)n.textContent=t;return n},icon=c=>{const n=document.createElement('i');n.className=c;n.setAttribute('aria-hidden','true');return n};
const validEmail=v=>{const s=clean(v);return !s||/sincorreo|no registrado/i.test(s)?'Sin correo registrado':s},digits=v=>{let d=clean(v).replace(/\D/g,'');if(d.length===10&&d.startsWith('3'))d='57'+d;return d},initials=n=>clean(n).split(/\s+/).filter(Boolean).slice(0,1).map(x=>x[0]).join('').toUpperCase()||'C';
const dateText=v=>{const s=clean(v);if(!s)return'Sin fecha';if(/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toLocaleDateString('es-CO',{day:'numeric',month:'short',year:'numeric'})},paymentDate=v=>clean(v)||'N/A';
const orderNumber=i=>clean(i?.numero_op||i?.numero||i?.numero_orden||'S/N'),quoteNumber=i=>clean(i?.numero_cotizacion||i?.numero||'S/N'),docUrl=i=>clean(i?.pdf_url||i?.url||''),activeItems=items=>(Array.isArray(items)?items:[]).filter(i=>!/ANUL/i.test(clean(i?.estado))),root=()=>document.getElementById(rootId);
function safeCall(name,...args){const fn=window[name];if(typeof fn!=='function'){console.warn('Clientes 3.1: función heredada no disponible',name);return}try{return fn(...args)}catch(error){console.error('Clientes 3.1:',name,error);toast('No se pudo completar la acción')}}
function toast(message){let node=document.querySelector('.v31-toast');if(!node){node=el('div','v31-toast');document.body.appendChild(node)}node.textContent=message;node.classList.add('is-showing');clearTimeout(toastTimer);toastTimer=setTimeout(()=>node.classList.remove('is-showing'),1600)}
function closeDocumentMenus(except){document.querySelectorAll('.v31-doc-popover.is-open').forEach(menu=>{if(menu!==except)menu.classList.remove('is-open')})}document.addEventListener('click',()=>closeDocumentMenus());
function buildHeader(){const header=el('header','v31-header'),inner=el('div','v31-header-inner'),back=el('button','v31-back');back.type='button';back.setAttribute('aria-label','Volver a HomeEasy');back.append(icon('fa-solid fa-chevron-left'));back.onclick=()=>location.href='index.html';const title=el('div','v31-title'),logo=document.createElement('img');logo.src='triangulo.png';logo.alt='HomeEasy';title.append(logo,el('span','', 'Clientes'));const search=el('button','v31-new-search','Nueva búsqueda');search.type='button';search.onclick=()=>{safeCall('reiniciarBusqueda');const r=root();if(r){r.className='';r.replaceChildren()}};inner.append(back,title,search);header.append(inner);return header}
function showLoading(){const r=root();if(!r)return;r.className='is-visible';r.replaceChildren();const shell=el('main','v31-shell'),box=el('div','v31-loading');box.append(icon('fa-solid fa-circle-notch fa-spin'),el('div','', 'Consultando cliente…'));shell.append(box);r.append(buildHeader(),shell)}
function showError(message){const r=root();if(!r)return;r.className='is-visible';r.replaceChildren();const shell=el('main','v31-shell');shell.append(el('div','v31-card v31-empty',message||'No fue posible cargar el cliente.'));r.append(buildHeader(),shell)}
function contactText(c){return[clean(c?.nombre),`Cédula: ${clean(c?.cedula)}`,`Teléfono: ${clean(c?.telefono)}`,`Correo: ${validEmail(c?.email)}`,`Dirección: ${clean(c?.direccion)||'Sin dirección registrada'}`].join('\n')}
async function copyText(text){try{if(navigator.clipboard&&isSecureContext)await navigator.clipboard.writeText(text);else{const a=document.createElement('textarea');a.value=text;a.style.position='fixed';a.style.opacity='0';document.body.appendChild(a);a.select();document.execCommand('copy');a.remove()}toast('Datos copiados')}catch(error){toast('No se pudo copiar')}}
function openClientMenu(c){document.querySelector('.v31-menu')?.remove();const menu=el('div','v31-menu is-open'),sheet=el('div','v31-sheet'),edit=el('button','');edit.append(icon('fa-solid fa-pen'),el('span','', 'Editar cliente'));edit.onclick=()=>{menu.remove();safeCall('abrirModalEditar')};const copy=el('button','');copy.append(icon('fa-regular fa-copy'),el('span','', 'Copiar datos'));copy.onclick=()=>{menu.remove();copyText(contactText(c))};const share=el('button','');share.append(icon('fa-solid fa-share-nodes'),el('span','', 'Compartir'));share.onclick=async()=>{menu.remove();const text=contactText(c);if(navigator.share){try{await navigator.share({title:'Cliente HomeEasy',text});return}catch(e){if(e?.name==='AbortError')return}}copyText(text)};const cancel=el('button','v31-cancel','Cancelar');cancel.onclick=()=>menu.remove();sheet.append(edit,copy,share,cancel);menu.append(sheet);menu.onclick=e=>{if(e.target===menu)menu.remove()};document.body.append(menu)}
function buildContact(c){const card=el('section','v31-card v31-contact'),identity=el('div','v31-identity'),avatar=el('div','v31-avatar',initials(c?.nombre)),badge=el('span','v31-avatar-badge'),brand=document.createElement('img');brand.src='triangulogold.png';brand.alt='HomeEasy';badge.append(brand);avatar.append(badge);const who=el('div','');who.append(el('h1','v31-name',clean(c?.nombre)||'Cliente'),el('div','v31-id-label','Cédula'),el('div','v31-id',clean(c?.cedula)||'Sin identificación'));const more=el('button','v31-more');more.type='button';more.setAttribute('aria-label','Opciones del cliente');more.append(icon('fa-solid fa-ellipsis'));more.onclick=()=>openClientMenu(c);identity.append(avatar,who,more);card.append(identity);const grid=el('div','v31-contact-grid'),phone=el('a','v31-contact-item'),phoneDigits=digits(c?.telefono);phone.href=phoneDigits?'tel:+'+phoneDigits:'#';const pi=el('div','v31-contact-icon');pi.append(icon('fa-solid fa-phone'));const pt=el('div','');pt.append(el('div','v31-contact-label','Teléfono'),el('div','v31-contact-value',clean(c?.telefono)||'No registrado'));phone.append(pi,pt);const addr=el('div','v31-contact-item'),ai=el('div','v31-contact-icon');ai.append(icon('fa-solid fa-location-dot'));const at=el('div','');at.append(el('div','v31-contact-label','Dirección'),el('div','v31-contact-value',clean(c?.direccion)||'Sin dirección registrada'));addr.append(ai,at);grid.append(phone,addr);card.append(grid);const email=el('div','v31-email'),ei=el('div','v31-contact-icon');ei.append(icon('fa-regular fa-envelope'));email.append(ei,el('span','',validEmail(c?.email)));card.append(email);const actions=el('div','v31-contact-actions'),wa=el('button','v31-whatsapp');wa.type='button';wa.append(icon('fa-brands fa-whatsapp'),el('span','', 'WhatsApp'));wa.onclick=()=>phoneDigits?window.open('https://wa.me/'+phoneDigits,'_blank','noopener,noreferrer'):toast('Sin teléfono válido');const bottomMore=el('button','v31-more-bottom');bottomMore.type='button';bottomMore.setAttribute('aria-label','Más opciones');bottomMore.append(icon('fa-solid fa-ellipsis'));bottomMore.onclick=()=>openClientMenu(c);actions.append(wa,bottomMore);card.append(actions);return card}
function buildSummary(orders){const valid=activeItems(orders),total=valid.reduce((sum,item)=>sum+Math.max(0,number(item?.total)),0),pending=valid.reduce((sum,item)=>sum+Math.max(0,number(item?.saldo)),0),section=el('section','v31-summary'),ico=el('div','v31-summary-icon');ico.append(icon('fa-solid fa-bag-shopping'));const text=el('div','v31-summary-text'),b=el('span','');b.append(document.createTextNode('Comprado '),el('strong','',money(total)));const p=el('span','');p.append(document.createTextNode('Pendiente '),el('span','pending',money(pending)));text.append(b,el('span','v31-dot','•'),p);section.append(ico,text);return section}
function statusClass(state){const s=clean(state).toUpperCase();if(/ANUL/.test(s))return' is-cancelled';if(/COMPLET|PAGAD|CERRAD|ENTREGAD/.test(s))return' is-complete';return''}
function documentOptions(prefix,item){const state=clean(item?.estado||'REGISTRADO').toUpperCase(),converted=prefix==='COT'&&state.includes('CONVERTIDA');return{edit:state!=='ANULADA'&&!converted,review:state!=='ANULADA'}}
function buildDocumentMenu(prefix,item){const options=documentOptions(prefix,item),num=prefix==='OP'?orderNumber(item):quoteNumber(item),wrap=el('div','v31-order-head-actions'),status=el('span','v31-status'+statusClass(item?.estado),clean(item?.estado||(prefix==='OP'?'REGISTRADO':'REGISTRADA')).toUpperCase());wrap.append(status);if(!options.edit&&!options.review)return wrap;const trigger=el('button','v31-doc-more');trigger.type='button';trigger.setAttribute('aria-label',`Opciones ${prefix} ${num}`);trigger.append(icon('fa-solid fa-ellipsis-vertical'));const pop=el('div','v31-doc-popover');if(options.edit){const edit=el('button','v31-doc-option');edit.type='button';edit.append(icon('fa-solid fa-pen-to-square'),el('span','', 'Editar'));edit.onclick=e=>{e.stopPropagation();pop.classList.remove('is-open');safeCall('confirmarEdicion',prefix,num)};pop.append(edit)}if(options.review){const review=el('button','v31-doc-option is-danger');review.type='button';review.append(icon('fa-solid fa-shield-halved'),el('span','', 'Revisar anulación'));review.onclick=e=>{e.stopPropagation();pop.classList.remove('is-open');safeCall('confirmarAnulacion',prefix,num)};pop.append(review)}trigger.onclick=e=>{e.stopPropagation();const opening=!pop.classList.contains('is-open');closeDocumentMenus(pop);pop.classList.toggle('is-open',opening)};pop.onclick=e=>e.stopPropagation();wrap.append(trigger,pop);return wrap}
function paymentReceiptLabel(p){const receipt=clean(p?.recibo);if(receipt.toUpperCase()==='INICIAL')return'Abono inicial';return`R.C. ${receipt||'N/A'}`}
function paymentIconClass(p){return clean(p?.recibo).toUpperCase()==='INICIAL'?'fa-solid fa-wallet':'fa-solid fa-receipt'}
function buildPaymentRow(payment){const initial=clean(payment?.recibo).toUpperCase()==='INICIAL',hasPdf=!initial&&Boolean(clean(payment?.url)),row=el('div','v31-payment-row'+(hasPdf?' is-clickable':'')),left=el('div','v31-payment-left'),ic=el('div','v31-payment-icon');ic.append(icon(paymentIconClass(payment)));const name=el('div','v31-payment-name',paymentReceiptLabel(payment));if(clean(payment?.tipoRegistro).toUpperCase()==='TRASLADO_CREDITO')name.append(el('span','v31-payment-state is-transfer','TRASLADO'));const state=clean(payment?.estado);if(state&&!/ACTIVO|SIN_PAGO/i.test(state))name.append(el('span','v31-payment-state',state.replace(/_/g,' ')));if(hasPdf)name.append(icon('fa-regular fa-eye v31-payment-eye'));left.append(ic,name);row.append(left,el('div','v31-payment-date',paymentDate(payment?.fecha)),el('div','v31-payment-amount',money(payment?.valor)));if(hasPdf){row.setAttribute('role','button');row.tabIndex=0;row.setAttribute('aria-label',`Ver recibo ${clean(payment?.recibo)}`);const open=()=>safeCall('abrirVisorPDF',payment.url);row.onclick=open;row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}}return row}
function buildHistory(item){const details=Array.isArray(item?.abonos_detalle)?item.abonos_detalle:[],total=Math.max(0,number(item?.total)),saldo=Math.max(0,number(item?.saldo)),paid=Math.max(0,total-saldo),panel=el('div','v31-history-panel'),box=el('div','v31-history-box'),title=el('div','v31-history-title');title.append(icon('fa-solid fa-clock-rotate-left'),el('span','', 'Historial de pagos'));box.append(title);if(details.length)details.forEach(payment=>box.append(buildPaymentRow(payment)));else box.append(el('div','v31-empty-history',paid>0?'El valor abonado está registrado, pero no hay recibos detallados.':'No hay abonos registrados.'));const totalRow=el('div','v31-payment-total');totalRow.append(el('span','', 'Total abonado'),el('strong','',money(paid)));box.append(totalRow);panel.append(box);const toggle=el('button','v31-history-toggle');toggle.type='button';toggle.setAttribute('aria-expanded','false');toggle.append(icon('fa-solid fa-clock-rotate-left'),el('span','', 'Historial de abonos'),el('span','v31-history-count',String(details.length)),icon('fa-solid fa-chevron-down v31-history-chevron'));toggle.onclick=()=>{const open=!panel.classList.contains('is-open');panel.classList.toggle('is-open',open);toggle.setAttribute('aria-expanded',String(open))};return{panel,toggle}}
function buildOrder(item){const card=el('article','v31-card v31-order'),head=el('div','v31-order-head');head.append(el('div','v31-order-code','OP '+orderNumber(item)),buildDocumentMenu('OP',item));card.append(head);const layout=el('div','v31-order-layout'),intro=el('div','v31-order-intro');intro.append(el('div','v31-order-desc',clean(item?.detalle||item?.descripcion)||'Sin detalles'));const date=el('div','v31-order-date');date.append(icon('fa-regular fa-calendar-days'),el('span','',dateText(item?.fecha)));intro.append(date);const total=Math.max(0,number(item?.total)),saldo=Math.max(0,number(item?.saldo)),cancelled=/ANUL/i.test(clean(item?.estado)),paid=cancelled?0:Math.max(0,total-saldo),pct=total>0?Math.max(0,Math.min(100,Math.round(paid/total*100))):0,finance=el('div','v31-finance'),left=el('div','v31-finance-left');left.append(el('div','v31-finance-label','Total'),el('div','v31-total',money(total)));const right=el('div',''),ph=el('div','v31-paid-head');ph.append(el('strong','',`Abonado ${money(paid)}`),el('span','',pct+'%'));const progress=el('div','v31-progress'),bar=el('span','');bar.style.width=pct+'%';progress.append(bar);right.append(ph,progress,el('div','v31-balance-label','Saldo'),el('div','v31-balance',cancelled?'Orden anulada':money(saldo)));finance.append(left,right);layout.append(intro,finance);card.append(layout);const history=buildHistory(item),actions=el('div','v31-order-actions'),url=docUrl(item),view=el('button','v31-view-op');view.type='button';view.append(icon('fa-regular fa-eye'),el('span','',url?'Ver OP':'Sin PDF'));if(url)view.onclick=()=>safeCall('abrirVisorPDF',url);else view.disabled=true;actions.append(history.toggle,view);card.append(actions,history.panel);return card}
function buildQuote(item){const card=el('article','v31-card v31-quote'),head=el('div','v31-order-head');head.append(el('div','v31-order-code','COT '+quoteNumber(item)),buildDocumentMenu('COT',item));card.append(head,el('div','v31-order-desc',clean(item?.detalle||item?.descripcion)||'Sin detalles'));const date=el('div','v31-order-date');date.append(icon('fa-regular fa-calendar-days'),el('span','',dateText(item?.fecha)));card.append(date);const bottom=el('div','v31-quote-total'),amount=el('div','');amount.append(el('div','v31-finance-label','Valor'),el('div','v31-quote-value',money(item?.total)));const actions=el('div','v31-quote-actions'),url=docUrl(item);if(url){const pdf=el('button','v31-small-btn');pdf.type='button';pdf.append(icon('fa-regular fa-eye'),el('span','', 'Ver PDF'));pdf.onclick=()=>safeCall('abrirVisorPDF',url);actions.append(pdf)}const state=clean(item?.estado).toUpperCase();if(!/CONVERTIDA|ANUL/.test(state)){const link=document.createElement('a');link.className='v31-small-btn';link.href='pedido.html?cotizacion='+encodeURIComponent(quoteNumber(item));link.append(icon('fa-solid fa-arrow-right-arrow-left'),el('span','', 'A OP'));actions.append(link)}bottom.append(amount,actions);card.append(bottom);return card}
function render(data){const r=root();if(!r)return;const client=data?.cliente||{},orders=Array.isArray(data?.ordenes)?data.ordenes:[],quotes=Array.isArray(data?.cotizaciones)?data.cotizaciones:[];r.className='is-visible';r.replaceChildren();const shell=el('main','v31-shell');shell.append(buildContact(client),buildSummary(orders));const tabs=el('div','v31-tabs'),ordersButton=el('button','v31-tab is-active'),quotesButton=el('button','v31-tab');ordersButton.type=quotesButton.type='button';ordersButton.append(el('span','', 'Órdenes'),el('span','v31-count',String(orders.length)));quotesButton.append(el('span','', 'Cotizaciones'),el('span','v31-count',String(quotes.length)));tabs.append(ordersButton,quotesButton);shell.append(tabs);const ordersPanel=el('section','v31-panel is-active'),quotesPanel=el('section','v31-panel');if(orders.length)orders.forEach(item=>ordersPanel.append(buildOrder(item)));else ordersPanel.append(el('div','v31-card v31-empty','Sin órdenes registradas.'));if(quotes.length)quotes.forEach(item=>quotesPanel.append(buildQuote(item)));else quotesPanel.append(el('div','v31-card v31-empty','Sin cotizaciones registradas.'));ordersButton.onclick=()=>{ordersButton.classList.add('is-active');quotesButton.classList.remove('is-active');ordersPanel.classList.add('is-active');quotesPanel.classList.remove('is-active')};quotesButton.onclick=()=>{quotesButton.classList.add('is-active');ordersButton.classList.remove('is-active');quotesPanel.classList.add('is-active');ordersPanel.classList.remove('is-active')};shell.append(ordersPanel,quotesPanel);r.append(buildHeader(),shell)}
window.fetch=async function(input,init){const url=typeof input==='string'?input:(input&&input.url)||'',history=/[?&]tipo=HISTORIAL_CLIENTE(?:&|$)/i.test(url);if(history)showLoading();try{const response=await originalFetch(input,init);if(history)response.clone().json().then(data=>data&&data.status==='found'?render(data):showError('Cliente no encontrado.')).catch(()=>showError('No fue posible interpretar la respuesta del cliente.'));return response}catch(error){if(history)showError('Error de conexión al consultar el cliente.');throw error}};
window.addEventListener('DOMContentLoaded',()=>document.body.classList.add('clientes-connected-v31'),{once:true});window.__HomeEasyClientes31={render};
})();
</script>
'''

insert_at = source.rfind("</head>")
if insert_at < 0: raise SystemExit("No se encontró </head>")
source = source[:insert_at] + CSS + "\n" + JS + "\n" + source[insert_at:]
required_output_markers = ["Historial de abonos", "Historial de pagos", "fa-regular fa-eye", "confirmarEdicion", "confirmarAnulacion", "abrirVisorPDF", "EJECUTAR_ANULACION_SEGURA", ".v31-new-search:hover", ".v31-order-actions", "v31-doc-popover"]
missing_output = [m for m in required_output_markers if m not in source]
if missing_output: raise SystemExit("La vista conectada perdió marcadores: " + ", ".join(missing_output))
OUTPUT.write_text(source, encoding="utf-8")
print(f"Generated {OUTPUT.name}: {len(source)} bytes")
