from pathlib import Path

path = Path('scripts/patch_seguimiento_fluid_10f.py')
source = path.read_text(encoding='utf-8')
old = '''old_success = ''' + "'''" + '''                    aplicarFiltros();\\n                } else {\\n''' + "'''" + '''\nnew_success = ''' + "'''" + '''                    window.dispatchEvent(new CustomEvent('homeeasy:seguimiento-updated', {\\n                        detail: { numero: String(numero), archived: Boolean(removerDePantalla), noteChanged: payloadData.notasSeguimiento !== undefined }\\n                    }));\\n                    aplicarFiltros();\\n                } else {\\n''' + "'''" + '''\nif page.count(old_success) != 1:\n    raise SystemExit(f'seguimiento update success anchor mismatch: {page.count(old_success)}')\npage = page.replace(old_success, new_success, 1)\n'''
new = '''old_success = ''' + "'''" + '''                    const index = allCotizaciones.findIndex(c => String(c.numero) === String(numero));\\n                    if (index !== -1) {\\n                        if (payloadData.notasSeguimiento !== undefined) {\\n                            allCotizaciones[index].notas_seguimiento = payloadData.notasSeguimiento;\\n                        }\\n                        if (removerDePantalla) {\\n                            allCotizaciones.splice(index, 1);\\n                        }\\n                    }\\n                    aplicarFiltros();\\n                } else {\\n''' + "'''" + '''\nnew_success = ''' + "'''" + '''                    const index = allCotizaciones.findIndex(c => String(c.numero) === String(numero));\\n                    if (index !== -1) {\\n                        if (payloadData.notasSeguimiento !== undefined) {\\n                            allCotizaciones[index].notas_seguimiento = payloadData.notasSeguimiento;\\n                        }\\n                        if (removerDePantalla) {\\n                            allCotizaciones.splice(index, 1);\\n                        }\\n                    }\\n                    window.dispatchEvent(new CustomEvent('homeeasy:seguimiento-updated', {\\n                        detail: { numero: String(numero), archived: Boolean(removerDePantalla), noteChanged: payloadData.notasSeguimiento !== undefined }\\n                    }));\\n                    aplicarFiltros();\\n                } else {\\n''' + "'''" + '''\nif page.count(old_success) != 1:\n    raise SystemExit(f'seguimiento update success anchor mismatch: {page.count(old_success)}')\npage = page.replace(old_success, new_success, 1)\n'''
if source.count(old) != 1:
    raise SystemExit(f'patch success block mismatch: {source.count(old)}')
path.write_text(source.replace(old, new, 1), encoding='utf-8')
